name: Develop Coverage

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "**/*.md"

permissions:
  contents: read

jobs:
  develop-coverage:
    uses: ./.github/workflows/_coverage.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
