// Generated by dts-bundle-generator v9.5.1

declare function _default({
	input,
	keyword,
	threshold,
}: {
	input: string
	keyword: string
	threshold?: number
}): Promise<{
	score: number
	additionalFields: {
		bestKeyword: string
		bestSubstring: string
		threshold: number
		isInjection: boolean
	}
}>

export { _default as default }

export {}
