# Builds the pyrit environment and runs partner integration tests. Partner integration tests are to ensure that we
# are not breaking any contract between PyRIT and its partners.

trigger: none

schedules:
- cron: "0 6 * * *"  # 6 AM UTC = 10 PM PST (UTC-8)
  displayName: Partner Integration Tests Daily at 06:00 AM UTC (10:00 PM PST)
  branches:
    include:
      - main
  always: true

jobs:
- template: test-job-template.yml
  parameters:
    jobName: PartnerIntegrationTests
    jobDisplayName: "Builds the pyrit environment and runs partner integration tests"
    testAzureSubscription: 'integration-test-service-connection'
    newDir: partner_integration_test_directory
    testsFolder: partner_integration
    makeTarget: partner-integration-test
