# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

"""
add display_group_map_json to ScenarioResultEntries.

Revision ID: e373726d391b
Revises: ab8f2c1a9d07
Create Date: 2026-04-23 11:32:09.031850
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e373726d391b"
down_revision: str | None = "ab8f2c1a9d07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this schema upgrade."""
    # ### commands auto generated by Alembic and reviewed by author###
    op.add_column(
        "ScenarioResultEntries",
        sa.Column("display_group_map_json", sa.Unicode(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this schema upgrade."""
    # ### commands auto generated by Alembic and reviewed by author ###
    op.drop_column("ScenarioResultEntries", "display_group_map_json")
    # ### end Alembic commands ###
