# -*- coding: utf-8 -*-
"""Regenerate `web/demo-fixtures.js` from the live registry.

The fixture is what the console renders when the gateway is not answering. It
existed as a hand-pasted blob, which meant every registry change silently made
the offline console a liar. This script makes it reproducible: run it after any
change to a capability name, a rail, or the coverage registry.

    python3 scripts/build_fixtures.py

The three `streams` scripts are NOT generated - they are hand-authored to
exercise the three shapes the cascade can take, and there is no registry that
knows them. They are read out of the existing file and written back unchanged,
so this script never destroys them.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PLATFORM = HERE.parent
sys.path.insert(0, str(PLATFORM))

TARGET = PLATFORM / "web" / "demo-fixtures.js"

HEADER = """\
// A snapshot of the real capability registry, used ONLY when the gateway is not
// answering, so the console's rendering can be exercised without it. It is not a
// cache and it is never mixed with live data: `state.source` flips to
// 'fixtures', the top bar and a page banner say so, and the streaming view
// labels every fixture run as a replay rather than a judgement.
//
// GENERATED by scripts/build_fixtures.py from afni_rai.registry - do not edit
// the `coverage` or `rails` blocks by hand. The three `streams` scripts ARE
// hand-authored (no registry knows them) and are preserved across regeneration.
"""


def existing_streams() -> dict:
    """The hand-authored stream scripts from the current file."""
    if not TARGET.exists():
        return {}
    m = re.search(r"export const FIXTURES = (\{.*?\});\s*$", TARGET.read_text(), re.S)
    if not m:
        return {}
    return json.loads(m.group(1)).get("streams", {})


def build() -> dict:
    from afni_rai.gateway.app import create_app  # noqa: F401  (registry side effects)
    from afni_rai.gateway.app import Gateway
    from afni_rai.registry import repositories

    gateway = Gateway()
    return {
        "coverage": gateway.coverage(),
        "repositories": repositories.status(),
        "rails": {"rails": gateway.rail_rows()},
        "streams": existing_streams(),
    }


def main() -> int:
    data = build()
    body = json.dumps(data, separators=(",", ":"), sort_keys=False)
    TARGET.write_text(f"{HEADER}\nexport const FIXTURES = {body};\n")
    print(f"wrote {TARGET.relative_to(PLATFORM)}  "
          f"({TARGET.stat().st_size / 1024:.0f} KB, "
          f"{len(data['rails']['rails'])} rails, "
          f"{len(data['streams'])} hand-authored streams preserved)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
