import { makeStyles, tokens } from '@fluentui/react-components'
import { mobileTouchTarget, mobileTouchTargetHeight } from '../../styles/touchTargets'

export const useChatInputAreaStyles = makeStyles({
  root: {
    padding: `${tokens.spacingVerticalXL} ${tokens.spacingHorizontalXXL}`,
    backgroundColor: tokens.colorNeutralBackground2,
  },
  inputContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalM,
    maxWidth: '900px',
    margin: '0 auto',
  },
  attachmentsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalXXS,
  },
  attachmentRow: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXXS,
  },
  attachmentContent: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXXS,
    flex: 1,
    minWidth: 0,
  },
  attachmentGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalXXS,
  },
  attachmentChip: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXXS,
    padding: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalS}`,
    backgroundColor: tokens.colorNeutralBackground4,
    borderRadius: tokens.borderRadiusLarge,
  },
  inputWrapper: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: tokens.colorNeutralBackground3,
    borderRadius: '28px',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    overflow: 'hidden',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    ':focus-within': {
      borderTopColor: tokens.colorBrandStroke1,
      borderRightColor: tokens.colorBrandStroke1,
      borderBottomColor: tokens.colorBrandStroke1,
      borderLeftColor: tokens.colorBrandStroke1,
      boxShadow: `0 0 0 2px ${tokens.colorBrandBackground2}`,
    },
  },
  inputColumns: {
    display: 'flex',
    alignItems: 'center',
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalL}`,
  },
  columnLeft: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalS,
    alignItems: 'center',
    marginRight: tokens.spacingHorizontalS,
    alignSelf: 'center',
  },
  columnCenter: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minWidth: 0,
    gap: tokens.spacingVerticalXS,
  },
  columnRight: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalS,
    alignItems: 'center',
    marginLeft: tokens.spacingHorizontalS,
    alignSelf: 'center',
  },
  textRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: tokens.spacingHorizontalXXS,
  },
  convertedRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: tokens.spacingHorizontalXXS,
  },
  textInput: {
    flex: 1,
    backgroundColor: 'transparent',
    border: 'none',
    outline: 'none',
    fontSize: tokens.fontSizeBase300,
    fontFamily: tokens.fontFamilyBase,
    color: tokens.colorNeutralForeground1,
    resize: 'none',
    minHeight: '24px',
    maxHeight: '60vh',
    overflowY: 'auto',
    ...mobileTouchTargetHeight,
    '::placeholder': {
      color: tokens.colorNeutralForeground4,
    },
    '::-webkit-scrollbar': {
      width: '8px',
    },
    '::-webkit-scrollbar-track': {
      backgroundColor: 'transparent',
    },
    '::-webkit-scrollbar-thumb': {
      backgroundColor: tokens.colorNeutralStroke1,
      borderRadius: '4px',
    },
  },
  textInputShared: {
    maxHeight: '30vh',
  },
  iconButton: {
    minWidth: '32px',
    width: '32px',
    height: '32px',
    padding: 0,
    borderRadius: '50%',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    ...mobileTouchTarget,
  },
  dismissBtn: {
    minWidth: '24px',
    width: '24px',
    height: '24px',
    padding: 0,
    ...mobileTouchTarget,
  },
  sendButton: {
    minWidth: '32px',
    width: '32px',
    height: '32px',
    padding: 0,
    borderRadius: '50%',
    ...mobileTouchTarget,
  },
  clearConversionButton: {
    minWidth: '32px',
    width: '32px',
    height: '32px',
    padding: 0,
    borderRadius: '50%',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground2,
    ...mobileTouchTarget,
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
      color: tokens.colorNeutralForeground1,
    },
  },
  singleTurnWarning: {
    display: 'flex',
    alignItems: 'center',
    color: tokens.colorPaletteYellowForeground2,
  },
  statusBanner: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: tokens.spacingHorizontalM,
    padding: `${tokens.spacingVerticalM} ${tokens.spacingHorizontalL}`,
    backgroundColor: tokens.colorNeutralBackground3,
    borderRadius: '28px',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  statusBannerText: {
    color: tokens.colorNeutralForeground2,
  },
  noTargetBanner: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: tokens.spacingHorizontalM,
    padding: `${tokens.spacingVerticalM} ${tokens.spacingHorizontalL}`,
    backgroundColor: tokens.colorPaletteRedBackground1,
    borderRadius: '28px',
    border: `1px solid ${tokens.colorPaletteRedBorder1}`,
  },
  noTargetText: {
    color: tokens.colorPaletteRedForeground1,
    fontWeight: tokens.fontWeightSemibold as unknown as string,
  },
  conversionLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXXS,
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
  },
  conversionText: {
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
    minWidth: 0,
    flex: 1,
    maxHeight: '80px',
    overflowY: 'auto',
  },
  convertedTextarea: {
    flex: 1,
    minWidth: 0,
    backgroundColor: 'transparent',
    border: 'none',
    outline: 'none',
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground1,
    resize: 'none',
    minHeight: '20px',
    maxHeight: '30vh',
    overflowY: 'auto',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    padding: 0,
    ...mobileTouchTargetHeight,
    '::-webkit-scrollbar': {
      width: '8px',
    },
    '::-webkit-scrollbar-track': {
      backgroundColor: 'transparent',
    },
    '::-webkit-scrollbar-thumb': {
      backgroundColor: tokens.colorNeutralStroke1,
      borderRadius: '4px',
    },
  },
  convertedFileBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalXXS,
    minWidth: 0,
  },
  convertedImagePreview: {
    display: 'block',
    maxHeight: '120px',
    maxWidth: '100%',
    borderRadius: tokens.borderRadiusSmall,
    objectFit: 'contain' as const,
    alignSelf: 'flex-start',
  },
  convertedAudioPreview: {
    display: 'block',
    width: '100%',
    maxWidth: '360px',
    height: '32px',
  },
  convertedVideoPreview: {
    display: 'block',
    maxHeight: '160px',
    maxWidth: '100%',
    borderRadius: tokens.borderRadiusSmall,
    alignSelf: 'flex-start',
  },
  convertedFilename: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground2,
  },
  openLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXXS,
    padding: `0 ${tokens.spacingHorizontalS}`,
    borderRadius: tokens.borderRadiusSmall,
    backgroundColor: tokens.colorBrandBackground,
    color: tokens.colorNeutralForegroundOnBrand,
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold as unknown as string,
    textDecoration: 'none',
    flexShrink: 0,
    height: '20px',
    ...mobileTouchTarget,
    ':hover': {
      backgroundColor: tokens.colorBrandBackgroundHover,
      color: tokens.colorNeutralForegroundOnBrand,
    },
  },
  unsupportedWarning: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXXS,
    color: tokens.colorPaletteYellowForeground2,
    fontSize: tokens.fontSizeBase200,
  },
  touchTarget: {
    ...mobileTouchTarget,
  },
  originalBadge: {
    display: 'inline-block',
    padding: `0 ${tokens.spacingHorizontalXS}`,
    marginRight: tokens.spacingHorizontalXS,
    borderRadius: tokens.borderRadiusSmall,
    backgroundColor: tokens.colorPaletteBlueBackground2,
    color: tokens.colorPaletteBlueForeground2,
    fontSize: tokens.fontSizeBase100,
    fontWeight: tokens.fontWeightSemibold as unknown as string,
    flexShrink: 0,
  },
  convertedBadge: {
    display: 'inline-block',
    padding: `0 ${tokens.spacingHorizontalXS}`,
    marginRight: tokens.spacingHorizontalXS,
    borderRadius: tokens.borderRadiusSmall,
    backgroundColor: tokens.colorPaletteGreenBackground2,
    color: tokens.colorPaletteGreenForeground2,
    fontSize: tokens.fontSizeBase100,
    fontWeight: tokens.fontWeightSemibold as unknown as string,
    flexShrink: 0,
  },
})
