# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

import logging
import mimetypes
from collections.abc import Callable
from pathlib import Path
from typing import Any, Literal

import aiofiles
import httpx

from pyrit.models import (
    Message,
    MessagePiece,
    construct_response_from_request,
)
from pyrit.prompt_target.common.target_capabilities import TargetCapabilities
from pyrit.prompt_target.common.target_configuration import TargetConfiguration
from pyrit.prompt_target.common.utils import limit_requests_per_minute
from pyrit.prompt_target.http_target.http_target import HTTPTarget

logger = logging.getLogger(__name__)


class HTTPXAPITarget(HTTPTarget):
    """
    A subclass of HTTPTarget that *only* does "API mode" (no raw HTTP request).
    This is a simpler approach for uploading files or sending JSON/form data.

    Additionally, if 'file_path' is not provided in the constructor,
    we attempt to pull it from the prompt's `converted_value`, assuming
    it's a local file path generated by a Converter (like PDFConverter).
    """

    _DEFAULT_CONFIGURATION: TargetConfiguration = TargetConfiguration(
        capabilities=TargetCapabilities(
            supports_multi_turn=True,
            input_modalities=frozenset(
                {
                    frozenset(["text"]),
                    frozenset(["image_path"]),
                    frozenset(["audio_path"]),
                    frozenset(["video_path"]),
                    frozenset(["binary_path"]),
                }
            ),
        )
    )

    def __init__(
        self,
        *,
        http_url: str,
        method: Literal["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"] = "POST",
        file_path: str | None = None,
        json_data: dict[str, Any] | None = None,
        form_data: dict[str, Any] | None = None,
        params: dict[str, Any] | None = None,
        headers: dict[str, str] | None = None,
        http2: bool | None = None,
        callback_function: Callable[..., Any] | None = None,
        max_requests_per_minute: int | None = None,
        custom_configuration: TargetConfiguration | None = None,
        **httpx_client_kwargs: Any,
    ) -> None:
        """
        Force the parent 'HTTPTarget' to skip raw http_request logic by setting http_request=None.

        Args:
            http_url (str): The URL to send the HTTP request to.
            method (str): The HTTP method to use (GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS). Defaults to "POST".
            file_path (str, Optional): Path to a file to upload. If not provided, we attempt to pull it from the
            prompt's `converted_value`.
            json_data (dict, Optional): JSON data to send in the request body (for POST/PUT/PATCH).
            form_data (dict, Optional): Form data to send in the request body (for POST/PUT/PATCH).
            params (dict, Optional): Query parameters to include in the request URL (for GET/HEAD).
            headers (dict, Optional): Headers to include in the request.
            http2 (bool, Optional): Whether to use HTTP/2. If None, defaults to False.
            callback_function (Callable, Optional): Function to parse the HTTP response.
            max_requests_per_minute (int, Optional): Maximum number of requests per minute.
            custom_configuration (TargetConfiguration, Optional): Override the default configuration for this target
            instance.
            Defaults to None.
            **httpx_client_kwargs: Additional keyword arguments to pass to the httpx.AsyncClient constructor.

        Raises:
            ValueError: If the HTTP method is invalid.
            ValueError: If file uploads are attempted with an HTTP method that does not support them.
        """
        super().__init__(
            http_request="",
            prompt_regex_string="",
            use_tls=True,
            callback_function=callback_function,
            max_requests_per_minute=max_requests_per_minute,
            custom_configuration=custom_configuration,
            **httpx_client_kwargs,
        )

        self.http_url = http_url
        self.method = method
        self.file_path = file_path
        self.json_data = json_data
        self.form_data = form_data
        self.params = params
        self.headers = headers or {}
        self.http2 = http2

        # Validate method
        if self.method not in {"GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"}:
            raise ValueError(f"Invalid HTTP method: {self.method}")

        # Validate file uploads (only `POST` and `PUT` allow file uploads)
        if self.file_path and self.method not in {"POST", "PUT"}:
            raise ValueError(f"File uploads are not allowed with HTTP method: {self.method}")

    @limit_requests_per_minute
    async def _send_prompt_to_target_async(self, *, normalized_conversation: list[Message]) -> list[Message]:
        """
        Override the parent's method to skip raw http_request usage,
        and do a standard "API mode" approach.

        - If file_path is set or we can deduce it from the message piece, we upload a file.
        - Otherwise, we send normal requests with JSON or form_data (if provided).

        Returns:
            list[Message]: A list containing the response object with generated text pieces.

        Raises:
            ValueError: If no `http_url` is provided.
            httpx.TimeoutException: If the request times out.
            httpx.RequestError: If the request fails.
            FileNotFoundError: If the specified file to upload is not found.
        """
        message = normalized_conversation[-1]
        message_piece: MessagePiece = message.message_pieces[0]

        # If user didn't set file_path, see if the PDF path is in converted_value
        if not self.file_path:
            possible_path = message_piece.converted_value
            if isinstance(possible_path, str) and Path(possible_path).exists():
                logger.info(f"HTTPXApiTarget: auto-using file_path from {possible_path}")
                self.file_path = possible_path
        elif not Path(self.file_path).exists():
            raise FileNotFoundError(f"File not found: {self.file_path}")

        if not self.http_url:
            raise ValueError("No `http_url` provided for HTTPXApiTarget.")

        http2_version = self.http2 if self.http2 is not None else False

        async with httpx.AsyncClient(http2=http2_version, **self.httpx_client_kwargs) as client:
            try:
                if self.file_path and Path(self.file_path).exists():
                    # Handle file upload (only for POST & PUT)
                    filename = Path(self.file_path).name
                    mime_type = mimetypes.guess_type(filename)[0] or "application/octet-stream"

                    async with aiofiles.open(self.file_path, "rb") as fp:
                        file_bytes = await fp.read()

                    files = {"file": (filename, file_bytes, mime_type)}

                    logger.info(f"HTTPXApiTarget: uploading file={filename} via {self.method} to {self.http_url}")

                    response = await client.request(
                        method=self.method,
                        url=self.http_url,
                        headers=self.headers,
                        params=self.params,
                        files=files,
                        follow_redirects=True,
                    )
                else:
                    # No file upload, handle based on HTTP method
                    logger.info(f"HTTPXApiTarget: sending {self.method} to {self.http_url} with possible JSON/form.")
                    response = await client.request(
                        method=self.method,
                        url=self.http_url,
                        headers=self.headers,
                        params=self.params,
                        json=self.json_data if self.method in {"POST", "PUT", "PATCH"} else None,
                        data=self.form_data if self.method in {"POST", "PUT", "PATCH"} else None,
                        follow_redirects=True,
                    )

            except httpx.TimeoutException:
                logger.error(f"Timeout error for URL: {self.http_url}")
                raise
            except httpx.RequestError as e:
                logger.error(f"Request failed: {e}")
                raise
            except FileNotFoundError as e:
                logger.error(f"File not found: {self.file_path}. Exception: {e}")
                raise

        response_content = response.content

        # If a callback function was set, let them parse the response
        if self.callback_function:
            response_content = self.callback_function(response=response)

        # Reuse parent's response object construction
        response_entry = construct_response_from_request(
            request=message_piece, response_text_pieces=[str(response_content)]
        )

        return [response_entry]
